### PR TITLE
Fix url to values.yaml in README.md in opensearch chart

### PR DESCRIPTION
**Pull request by gdm**
Signed-off-by: Dmytro Gorbunov <dmytro.gorbunov@gmail.com>

### Description
Fix URLs to values.yaml in README.md
 
### Issues Resolved
URLs fixed
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
@gdm you need to bump the charts version and add the changelog.
Thanks.

**Comment by gdm** [comment]
Done

**Review by peterzhuamazon — APPROVED** [review]

**Review by DandyDeveloper — APPROVED** [review]
Looks good, but didn't we determine that README related changes don't need a CHANLOG?

**Comment by TheAlgo** [comment]
Yes thats correct, we should not even bump the chart version for README changes. I remember some one doing a README change and previously it did not require a bump.

**Comment by gdm** [comment]
Can you guys talk together and decide whether you need version bump for this change ?

**Comment by DandyDeveloper** [comment]
@gdm We need neither. Just the README update.

**Comment by peterzhuamazon** [comment]
> Yes thats correct, we should not even bump the chart version for README changes. I remember some one doing a README change and previously it did not require a bump.

We need to tweak the CI to not run when README is changed.

**Pull request merged**
