### PR TITLE
fix ingress helm validation error

### PR DESCRIPTION
**Pull request by atalakey4work**
### Description
fix ingress helm validation error
 
### Issues Resolved
fix ingress helm validation error below:
error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend.service): unknown field "port:number" in io.k8s.api.networking.v1.IngressServiceBackend
 
### Check List
- [x] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [x] Helm chart version bumped
- [x] Helm chart `CHANGELOG.md` updated to reflect change

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Hi @atalakey4work what is the reason of closing these PRs?
Seems like it fix an issue talked about in https://github.com/opensearch-project/helm-charts/pull/322.
If you have issues with version bump I can do it once you open the PR.

Thanks.

**Comment by atalakey4work** [comment]
Hello @peterzhuamazon,

I mistakenly deleted the fork which in turns closed the PR. The fix is pretty simple, you have to remove the trailing dash “-“ from the else close under “charts/opensearch-dashboards/templates/ingress.yaml” line 51.

**Comment by peterzhuamazon** [comment]
Sure @atalakey4work we will raise the PR based on your changes.
Thanks.

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/helm-charts/pull/326

**Pull request closed without merging**
