### PR TITLE
fix: deprecated api migration versions

### LINKED ISSUE #157: [BUG][opensearch] Chart not installing in PSP enabled kubernetes clusters >= 1.21.
**Describe the bug**
Chart not installing in Kubernetes clusters >= 1.21 with PodSecurityPolicies enabled.

This is because the chart want's to use `apiVersion: policy/v1`. However there is no such apiVersion and there never will be. podSecurityPolicys have been deprecated, because they will be removed completely in future Kubernetes versions.

**To Reproduce**
1. Requirement: PSP enabled kubernetes cluster >= 1.21
2. `helm install opensearch --set=podSecurityPolicy.create=true --set=rbac.create=true opensearch/opensearch`
3. `Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "PodSecurityPolicy" in version "policy/v1"`

**Expected behavior**
Chart should install with a warning about the deprecation.

**Chart Name**
opensearch

**Host/Environment (please complete the following information):**
 - Helm Version: 3.7.1
 - Kubernetes Version: 1.21.5

**Additional context**
Suggested patch:

```patch
--- a/charts/opensearch/templates/podsecuritypolicy.yaml
+++ b/charts/opensearch/templates/podsecuritypolicy.yaml
@@ -1,10 +1,6 @@
 {{- if .Values.podSecurityPolicy.create -}}
 {{- $fullName := include "opensearch.uname" . -}}
-{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion -}}
-apiVersion: policy/v1
-{{- else -}}
 apiVersion: policy/v1beta1
-{{- end }}
 kind: PodSecurityPolicy
 metadata:
   name: {{ default $fullName .Values.podSecurityPolicy.name | quote }}
```

### PR DESCRIPTION
**Pull request by etenzy**
Signed-off-by: Michael Rödel <hello@mroedel.de>

### Description
Change the semverCompare for PodSecurityPolicy according to https://kubernetes.io/docs/reference/using-api/deprecation-guide/
 
### Issues Resolved
#157 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Hi @etenzy you need to update the charts version as well as the changelog.

See #152 example.

Thanks.

**Comment by etenzy** [comment]
done

**Comment by peterzhuamazon** [comment]
Not sure why it is saying
```

  4e0002d3ebc98f09a3c46e36fff8169d0be6c4c4    Expected "etenzy <hello@mroedel.de>", but got "Michael Rödel <hello@mroedel.de>".
  026abcf602f8eadca45e8c828507e1dee81c86e7    Expected "etenzy <hello@mroedel.de>", but got "Michael Rödel <hello@mroedel.de>".

```

Can you check what is happening with your git config username?

Thanks.

**Comment by etenzy** [comment]
rebased

**Comment by peterzhuamazon** [comment]
@etenzy conflicts as another PR with version 1.5.2 already in.
Thanks.

**Review by DandyDeveloper — APPROVED** [review]

**Comment by etenzy** [comment]
bumped the version

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Thanks @etenzy for the contribution, it is merged.

**Pull request merged**
