### PR TITLE
Fix path in securityConfig section on OpenSearch (values.yaml)

### PR DESCRIPTION
**Pull request by GRomR1**
Signed-off-by: Ruslan Gainanov <gromrx1@gmail.com>

### Description

When I put some configures into section 
```
securityConfig:
  config:
    data:
      config.yml: |-
        ....
```

The file config.yml will be created in path `/usr/share/opensearch/plugins/opensearch-security/securityconfig/`. OpenSearch didn't read this file. The content of this path is
```
sh-4.2$ ls -lah /usr/share/opensearch/plugins/opensearch-security/
total 44M
drwxr-xr-x. 1 opensearch opensearch    28 Oct 12 18:42 .
drwxr-xr-x. 1 opensearch opensearch    60 Oct 12 18:43 ..
-rw-r--r--. 1 opensearch opensearch   29K Jun 30 21:49 accessors-smart-2.4.7.jar
-rw-r--r--. 1 opensearch opensearch   56K Jun 30 21:49 aggs-matrix-stats-client-2.1.0.jar
-rw-r--r--. 1 opensearch opensearch  119K Jun 30 21:49 asm-9.1.jar
-rw-r--r--. 1 opensearch opensearch  5.7M Jun 30 21:49 bcprov-jdk15on-1.67.jar
```

I think the right path should be `/usr/share/opensearch/config/opensearch-security/`
```
sh-4.2$ ls -lah /usr/share/opensearch/config/opensearch-security/
total 72K
drwxr-x---. 2 opensearch opensearch  245 Jun 30 21:49 .
drwxr-xr-x. 1 opensearch opensearch   46 Oct 13 07:15 ..
-rw-rw----. 1 opensearch opensearch   50 Jun 30 21:49 action_groups.yml
-rw-rw----. 1 opensearch opensearch 2.0K Jun 30 21:49 allowlist.yml
-rw-rw----. 1 opensearch opensearch 2.5K Jun 30 21:49 audit.yml
-rw-rw----. 1 opensearch opensearch 9.8K Jun 30 21:49 config.yml
-rw-rw----. 1 opensearch opensearch 1.7K Jun 30 21:49 internal_users.yml
-rw-rw----. 1 opensearch opensearch  154 Jun 30 21:49 nodes_dn.yml
-rw-rw----. 1 opensearch opensearch  13K Jun 30 21:49 opensearch.yml.example
-rw-rw----. 1 opensearch opensearch 8.4K Jun 30 21:49 roles.yml
-rw-rw----. 1 opensearch opensearch  844 Jun 30 21:49 roles_mapping.yml
-rw-rw----. 1 opensearch opensearch  170 Jun 30 21:49 tenants.yml
-rw-rw----. 1 opensearch opensearch 2.0K Jun 30 21:49 whitelist.yml
```

### Check List
- [x] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [x] Helm chart version bumped
- [x] Helm chart `CHANGELOG.md` updated to reflect change

### CODE REVIEW

**Comment by GRomR1** [comment]
Attempt #2. I don't understand why but the previous PR has been closed when I try to add CHANGELOG and version

https://github.com/opensearch-project/helm-charts/pull/337

**Comment by prudhvigodithi** [comment]
Thanks @GRomR1 for the PR, LGTM, this we need not backport to 1.x, @TheAlgo and @peterzhuamazon can you take a look
?
Thank you

**Comment by peterzhuamazon** [comment]
Hi,

This is good, one more miss due to this change in 2.x:
https://github.com/opensearch-project/opensearch-plugins/issues/127

I am ok to have this in 2.x only. Thanks.

@GRomR1 could you please resolve the version issues, will merge then.

Thanks.

**Review by DandyDeveloper — APPROVED** [review]

**Comment by GRomR1** [comment]
@peterzhuamazon resolved.

@TheAlgo could you please look and approve the PR

**Comment by peterzhuamazon** [comment]
Waiting a new approval from @prudhvigodithi or @TheAlgo.
If no responses I will approve and fix the linting after I come back from Thanksgiving.

Thanks.

**Comment by prudhvigodithi** [comment]
Hey Thanks for the PR @GRomR1, LGTM, can you please resolve the conflicts?
Thank you

**Review by prudhvigodithi — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Trying to fix the linting here.

**Comment by peterzhuamazon** [comment]
Related to kind action need to update to 1.3.0.

**Comment by peterzhuamazon** [comment]
No need to backport this as it is 2.x + only changes

**Pull request merged**
