### PR TITLE
Added flag to create a network policy

### PR DESCRIPTION
**Pull request by Rubemlrm**
### Description
This change was relative to a new flag that will validate the need to create a network policy. I had an use case where the user accounts can't create network policies.
  
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Hi @Rubemlrm you need to bump charts version, add changelog, and signoff dco.
See this one as an example: #152 
Thanks.

**Comment by Rubemlrm** [comment]
> Hi @Rubemlrm you need to bump charts version, add changelog, and signoff dco. See this one as an example: #152 Thanks.

Thank you for the help. I think that now it's following the requirements. I had one question relative to the Changelog compare between versions, can you check if that it's the correct way? My question is relative to the links to the unreleased version, i've checked the issue #152 and tried follow that.
Another question i was only able to sign off the last commit, there is any way to sign of the previous one?

**Comment by TheAlgo** [comment]
> > Hi @Rubemlrm you need to bump charts version, add changelog, and signoff dco. See this one as an example: #152 Thanks.
> 
> Thank you for the help. I think that now it's following the requirements. I had one question relative to the Changelog compare between versions, can you check if that it's the correct way? My question is relative to the links to the unreleased version, i've checked the issue #152 and tried follow that.

Yes it is , just that you need to resolve the conflicts.

**Comment by Rubemlrm** [comment]
@TheAlgo just fixed the merge conflicts.

**Comment by peterzhuamazon** [comment]
Hi @Rubemlrm seems like you need to rebase to one commit then sign.
```
7ea9d3e650d4e4738498b8d603a5ea52d7f0a942    The sign-off is missing.
  a27bf3353893a5324429313d29a370275a7ad623    The sign-off is missing.
  722de7e7c338e2c6adb75ba9975a895de43b1224    The sign-off is missing.
  514defd49f7eb32e5a4b7a47603d0297ec3b3b43    The sign-off is missing.
```

**Comment by Rubemlrm** [comment]
i will create a new PR, to sign off the needed commits. I'm having some issues regarding the sign off of previous commits and to avoid any problem, i've closed this one and will create a new one.

**Pull request closed without merging**
