### PR TITLE
Add homepage and source urls to chart

### PR DESCRIPTION
**Pull request by viceice**
### Description
Backport of #455 
 
### Issues Resolved
none
 
### Check List
- [x] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [x] Helm chart version bumped
- [ ] Helm chart `CHANGELOG.md` updated to reflect change

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by TheAlgo — APPROVED** [review]
Nice change this is

**Comment by TheAlgo** [comment]
@prudhvigodithi  Please have a look when free. Thanks

**Comment by TheAlgo** [comment]
@viceice Please do update the Changelog. Thanks

**Comment by viceice** [comment]
> @viceice Please do update the Changelog. Thanks

sure, will try to do in next days

**Review by prudhvigodithi — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Thanks @viceice.

**Pull request merged**
