### PR TITLE
added changelog for 1.3.1 opensearch-dashboards

### PR DESCRIPTION
**Pull request by abhinavGupta16**
Signed-off-by: Abhinav Gupta <abhng@amazon.com>

### Description
Added changelog for 1.3.1 opensearch-dashboards release
 
### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/1885
 
### Check List
- [x] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [x] Helm chart version bumped
- [x] Helm chart `CHANGELOG.md` updated to reflect change

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Hey @abhinavGupta16 please change `appVersion`, to point to the latest version for dashboard.

**Review by prudhvigodithi — APPROVED** [review]

**Review by peterzhuamazon — CHANGES_REQUESTED** [review]
This is new release means minor bump

**Review by peterzhuamazon — APPROVED** [review]

**Comment by sastorsl** [comment]
Could the title of this PR be updated to reflect that it's actually 1.4.0?

**Comment by TheAlgo** [comment]
I agree with @sastorsl this commit message is not so good even if the version number was correct. Here the intent is to not add CHANGELOG but bump the version.

IMHO I don't prefer commits which has a past tense (Eg : `Bumped` , `Added`). If we see the default git commit those are always like commands (Eg : `Merge abc from cde`)

**Comment by TheAlgo** [comment]
Also @abhinavGupta16 in the issue attached I could find the details regarding helm update. There is no mention about the release in helm charts

**Comment by abhinavGupta16** [comment]
> I agree with @sastorsl this commit message is not so good even if the version number was correct. Here the intent is to not add CHANGELOG but bump the version.
> 
> IMHO I don't prefer commits which has a past tense (Eg : `Bumped` , `Added`). If we see the default git commit those are always like commands (Eg : `Merge abc from cde`)

Well, I don;t think tense matters as long as the message is conveyed. Also, the commit where the version is bumped has the commit message as bumped version to 1.4.0

**Comment by abhinavGupta16** [comment]
> Could the title of this PR be updated to reflect show that the actual version bump is the appVersion? "Bump to opensearch-dashboards-1.3-1 in helm release 1.4.0" for instance?

Good suggestion. I updated the title. It would make it easier to search for the PR

**Comment by TheAlgo** [comment]
> > Could the title of this PR be updated to reflect show that the actual version bump is the appVersion? "Bump to opensearch-dashboards-1.3-1 in helm release 1.4.0" for instance?
> 
> Good suggestion. I updated the title. It would make it easier to search for the PR

@abhinavGupta16 Do you mind changing to `Bump appversion to 1.3.1` or `Change default version to 1.3.1` instead of added changelog?

**Comment by TheAlgo** [comment]
@abhinavGupta16 Any update on this?

**Comment by peterzhuamazon** [comment]
I changed it.
```
Bump to opensearch-dashboards-1.3-1 in helm release 1.4.0
```
Thanks @sastorsl @TheAlgo

**Pull request merged**
