### PR TITLE
Update values.yaml - Rm whitespace DN

### PR DESCRIPTION
**Pull request by sebas-intellegens**
### Description
According to https://opensearch.org/docs/latest/security-plugin/configuration/security-admin/#configure-the-admin-certificate
there shouldn't be any whitespace in the distinguished name, so I assume it was not correct here?

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Hi @sebas-intellegens please bump the charts version and tick the box for DCO.
Thanks.

**Comment by TheAlgo** [comment]
@sebas-intellegens Will it be possible for you to fix the conflicts in this PR and if possible create an issue you faced because of this as well. Thanks

**Comment by peterzhuamazon** [comment]
Hi @sebas-intellegens please update the version for this PR thanks.

**Review by DandyDeveloper — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
> @sebas-intellegens seems like you miss the DCO check when pulling from main. Thanks.

Hi @sebas-intellegens can you just `git commit --amend --no-edit -s` then repush to resolve DCO checks?

Thanks.

**Review by TheAlgo — APPROVED** [review]
LGTM!!!

Reolved Merger conflicts as well 😁

**Comment by TheAlgo** [comment]
@sebas-intellegens can you please sign off the commit?

**Comment by sebas-intellegens** [comment]
> @sebas-intellegens can you please sign off the commit?

Literally never done this before

No idea how to do this for existing commits
I tried doing this
```sh
git commit --amend -s -c c4901e5939d96e3638004ccd12f445330ee654bd
git commit --amend -s -c 89c457a9de8361cbffe15d2788057fb518d0ea43
git commit --amend -s -c f8cf7e58a3af4c583e3d975a6af5bd9c34447bbe
```
for the commits mentioned [here](https://github.com/opensearch-project/helm-charts/runs/4130457209?check_suite_focus=true)

Hopefully this is what you mean

**Comment by peterzhuamazon** [comment]
> > @sebas-intellegens can you please sign off the commit?
> 
> Literally never done this before
> 
> No idea how to do this for existing commits I tried doing this
> 
> ```shell
> git commit --amend -s -c c4901e5939d96e3638004ccd12f445330ee654bd
> git commit --amend -s -c 89c457a9de8361cbffe15d2788057fb518d0ea43
> git commit --amend -s -c f8cf7e58a3af4c583e3d975a6af5bd9c34447bbe
> ```
> 
> for the commits mentioned [here](https://github.com/opensearch-project/helm-charts/runs/4130457209?check_suite_focus=true)
> 
> Hopefully this is what you mean

`git commit --amend --no-edit -s`

**Comment by sebas-intellegens** [comment]
> `git commit --amend --no-edit -s`

Thanks

I ran

```sh
git commit --amend --no-edit -s
git pull # Because 'Updates were rejected because the tip of your current branch is behind its remote counterpart.'
git commit --amend --no-edit -s
git push
```
from my fork
hopefully this worked :crossed_fingers:

**Comment by TheAlgo** [comment]
@sebas-intellegens Ouch. That did not work. Can you try amending again?

**Comment by sebas-intellegens** [comment]
Damn
Now I've tried
```sh
git commit --amend -s -c c4901e5939d96e3638004ccd12f445330ee654bd
git commit --amend -s -c 89c457a9de8361cbffe15d2788057fb518d0ea43
git commit --amend -s -c f8cf7e58a3af4c583e3d975a6af5bd9c34447bbe
git pull
git commit --amend --no-edit -s
git push
```
:crossed_fingers: 
Not sure how it is supposed to work, but it doesn't seem to have signed off the initial commits (the ones mentioned [here](https://github.com/opensearch-project/helm-charts/runs/4150625713?check_suite_focus=true)), I was hoping `git commit --amend -s -c <HASH>` would do that

**Comment by DandyDeveloper** [comment]
Looks good. I've got the CI running now.

**Comment by TheAlgo** [comment]
DCO is still failing 😢

**Comment by sebas-intellegens** [comment]
I created a new branch `patch3`, made the two changes I made here, committed it with `-s`, pushed and created a new PR using that branch here https://github.com/opensearch-project/helm-charts/pull/130
Maybe this will work :smile:

**Comment by TheAlgo** [comment]
Closing this PR in favour of #130

**Pull request closed without merging**
