### PR TITLE
Fix depricated roles

### PR DESCRIPTION
**Pull request by Sebor**
### Description
Rework deprecated node roles definition. 
Now in `values.yaml` roles are described as a list and there are no any deprecation warnings in logs.

### Related issues
- #122 

### Check List
- [ x ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Sebor** [comment]
Hi @TheAlgo, @peterzhuamazon, @smlx !
Could you review this PR?

**Comment by peterzhuamazon** [comment]
Hi @Sebor thanks for the PR could you please create an issue and link to this PR?
This would make it easier for people to check.

Also, seems like you need to sign DCO check, and bump your chart version.

Thanks.

**Comment by Sebor** [comment]
Hi @peterzhuamazon!
I've solved all remarks

**Review by DandyDeveloper — COMMENTED** [review]
I'll double check this one but looks good. One thing @Sebor looks like your IDE or something has instead a CRLF on all the `keys: {}` making your branch look significantly more verbose. 

Can you undo those changes?

**Comment by Sebor** [comment]
Hi @peterzhuamazon, @DandyDeveloper, @TheAlgo!
I was too stupid to overcome the git, so I've created a new PR. Please review that [one](https://github.com/opensearch-project/helm-charts/pull/124)

**Pull request closed without merging**
