### PR TITLE
fix: Handle log4j2 not being yaml (#110) and chart bump.

### LINKED ISSUE #110: [BUG][opensearch] log4j2.properties in values.yaml does not work with toYaml in configmap.yaml
**Describe the bug**
In the current chart for `opensearch-dashboards` it is not possible to template `log4j2.properties` as the `configmap.yaml` expects input to _be_ in yaml.
log4j2.properties is not yaml but has a `key = value` structure.

This makes it not possible to override the log4j configuration with the current chart.

**To Reproduce**
1. Add helm repo
2. Edit `values.yaml` and add `log4j2.properties` to `config`
3. `helm install`
4. See error, which is that the file is created without line breaks, which renders it unusable.

This happens because the log4j2.properties is _not_ YAML, but rather `key = value`.
Any yaml multiline trick does not work.

Error message from pod:

```
2021-10-28 12:28:14,202 main ERROR Invalid status level specified: ERROR APPENDER.CONSOLE.TYPE = CONSOLE APPENDER.CONSOLE.NAME = CONSOLE APPENDER.CONSOLE.LAYOUT.TYPE. Defaulting to ERROR.
```

**Expected behavior**
log4j2.properties to be created in a proper format.

**Chart Name**
opensearch - configmap

https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/templates/configmap.yaml#L11 - `toYaml`

**Screenshots**

Example config in `values.yaml`

```yaml
config:
  log4j2.properties:
    status = error
    appender.console.type = Console
    appender.console.name = console
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n
    rootLogger.level = info
    rootLogger.appenderRef.console.ref = console
    logger.plugins.security.name = com.amazon.dlic.auth.http.jwt
    logger.plugins.security.level = trace
```

Output from `helm install`

```yaml
config:
  log4j2.properties: status = error appender.console.type = Console appender.console.name
    = console appender.console.layout.type = PatternLayout appender.console.layout.pattern
    = [%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n rootLogger.level = info
    rootLogger.appenderRef.console.ref = console logger.plugins.security.name = com.amazon.dlic.auth.http.jwt
    logger.plugins.security.level = trace
```

configmap:

```yaml
data:
  log4j2.properties: |
    status = error appender.console.type = Console appender.console.name = console appender.console.layout.type
      = PatternLayout appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}]
      [%node_name]%marker %m%n rootLogger.level = info rootLogger.appenderRef.console.ref
      = console logger.plugins.security.name = com.amazon.dlic.auth.http.jwt logger.plugins.security.level
      = trace
```

Resulting file:

```bash
$ k exec -ti opensearch-1 -- bash -c "cat config/log4j2.properties"
status = error appender.console.type = Console appender.console.name = console appender.console.layout.type
  = PatternLayout appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}]
  [%node_name]%marker %m%n rootLogger.level = info rootLogger.appenderRef.console.ref
  = console logger.plugins.security.name = com.amazon.dlic.auth.http.jwt logger.plugins.security.level
  = trace
```

**Host/Environment (please complete the following information):**
 - Helm Version: 3.7.0
 - Kubernetes Version: 1.21.2

**Additional context**
Workaround would probably be to create a separate configmap and reference, but using it in `values.config` should also work.

### PR DESCRIPTION
**Pull request by sastorsl**
Bump chart (#110)

Signed-off-by: Stein Arne Storslett <sastorsl@users.noreply.github.com>

### Description
Render `log4j2.properties` properly when added to `values.yaml` / `config`.
The current version does a `toYaml`, but log4j2 is `key = value` based and not yaml so without this PR log4j2 will not be rendered properly (see issue for details).

Maintainers may adjust the Chart version as needs be, ie. to align with other PR's but please contact me for any other changes.

This PR _**replaces**_ PR #118 
 
### Issues Resolved
#110 
 
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by sastorsl** [comment]
@peterzhuamazon this PR replaces #118 and should be clean.

**Comment by DandyDeveloper** [comment]
@sastorsl I'm very quickly going to try out a change of my own to hopefully not need this odd conditional. 

If I can't get it working within 10-20 minutes of playing, I'll approve this.

**Comment by DandyDeveloper** [comment]
@sastorsl https://github.com/sastorsl/opensearch-helm-charts/pull/1

I made this PR against your branch with my tpl changes. 

The only problem with this: Technically it introduces a breaking change for anyone overwriting the values with their own values in a parent OR using `--set`. However, if we document this. It actually means we can also support templating config files off of other values in the file. 

@TheAlgo @mprimeaux Do you guys think this is a worthwhile "breaking" change to include for the sake of preventing this conditional?

**Comment by sastorsl** [comment]
Reviewed your PR @DandyDeveloper and it looks good to me, just a couple of comments with the changes to `values.yaml`.

With regards to breaking changes this was simple enough to fix, but I only tested my own use case, so if one of you could run through a couple of variants that would be great.

PS! I'm relying on on of these variants these days since I need to debug OIDC, so would be great if we could get this into the repo as soon as (safely) possible.

**Comment by TheAlgo** [comment]
@DandyDeveloper I agree with you and this is a breaking change, there might be people who might be using it directly.

**Comment by DandyDeveloper** [comment]
@sastorsl I think this works under minor as it's pretty unlikely to hit too many people too hard.

**Comment by TheAlgo** [comment]
@sastorsl Yes that is a go

**Comment by sastorsl** [comment]
Merged @DandyDeveloper 's PR and added some finishing touches.
Chart bumped to `1.3.1` (main is at `1.3.0` at the time of writing).

**Review by TheAlgo — APPROVED** [review]
Looks like because of this change we need to change the structure in CI as well

**Comment by TheAlgo** [comment]
Looks like because of this change we need to change the structure in CI as well. @sastorsl Will you be able to make the changes in CI as well?

**Review by TheAlgo — DISMISSED** [review]
Looks like because of this change we need to change the structure in CI as well. @sastorsl Will you be able to make the changes in CI as well?

**Comment by sastorsl** [comment]
@TheAlgo CI should be ready now.

**Review by DandyDeveloper — APPROVED** [review]

**Review by peterzhuamazon — CHANGES_REQUESTED** [review]
I have 2 concerns right here:
1. If breaking change, it should be minor version bump not patch version bump.
2. If this is a config change then README file should be updated.

Thanks.

**Comment by sastorsl** [comment]
@peterzhuamazon I've bumped to `1.4.0`.
The `README.md` already refers to `values.yaml`, where it is also explicitly - as pr this PR - stated what the formatting should be like.
Hope this satisfies your concerns.

**Comment by peterzhuamazon** [comment]
Thanks @sastorsl for the heads up, I have retriggered the tests and lets see how it goes.

**Comment by peterzhuamazon** [comment]
Hi @sastorsl due to merge of another PR seems like you need to resolve the conflicts.
Sorry about it.
Thanks.

**Comment by sastorsl** [comment]
@peterzhuamazon I've merge branch `main` into my fork and branch and resolved conflicts.
Hope you merge mine next now ;-)

**Review by peterzhuamazon — APPROVED** [review]
Thanks.

**Pull request merged**
