### PR TITLE
Opensearch dashboard configmap error:  `invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string"`

### PR DESCRIPTION
**Pull request by prudhvigodithi**
Signed-off-by: pgodithi <pgodithi@amazon.com>

### Description
Opensearch dashboard config map support both string and map format.
 
### Issues Resolved
https://github.com/opensearch-project/helm-charts/issues/295
 
### Check List
- [x] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [x] Helm chart version bumped
- [x] Helm chart `CHANGELOG.md` updated to reflect change

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Hey @viceice @DandyDeveloper this should fix the issue #295 
Now following both should work, can you please test with my fork @viceice 
```
config:
  opensearch_dashboards.yml: |
     server:
       name: dashboards
       host: 0.0.0.0
```

```
config:
  opensearch_dashboards.yml: 
     server:
       name: dashboards
       host: 0.0.0.0
```

@peterzhuamazon @bbarani @TheAlgo

**Review by TheAlgo — APPROVED** [review]

**Review by bbarani — APPROVED** [review]

**Comment by viceice** [comment]
will this be back ported to V1?

**Comment by peterzhuamazon** [comment]
> will this be back ported to V1?

https://github.com/opensearch-project/helm-charts/pull/301

**Comment by viceice** [comment]
thank you

**Pull request merged**
