### PR TITLE
Add lifecycle support in opensearch container

### PR DESCRIPTION
**Pull request by josephteddick**
### Description
I was looking to run the securityadmin.sh script automatically after the opensearch container is started up. However, the opensearch container in the StatefulSet did not have 'lifecycle' support. Added support to satisfy my use case, in addition to adding extra customization options to the chart.
 
### Issues Resolved
- [Enhancement][OpenSearch] #395
 
### Check List
- [x] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [x] Helm chart version bumped
- [x] Helm chart `CHANGELOG.md` updated to reflect change

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by TheAlgo** [comment]
@josephteddick Can you add an issue to it which describes these addition and if you have any use cases in mind?

**Review by TheAlgo — COMMENTED** [review]
Can we add some example in values.yaml and update the documentation to have better clarity on this feature?

**Comment by josephteddick** [comment]
@TheAlgo Thanks for getting back to me. I've created the issue [Enhancement][OpenSearch] #395 tracking why adding Lifecycle Hook support may be useful. I've also added a simple general use case example to the values. Let me know if there is anything else you need.

**Comment by prudhvigodithi** [comment]
Thanks for the PR @josephteddick LGTM!, can you please also test with helm upgrade, just want to make sure its not a breaking change for existing helm charts. @TheAlgo you also review this PR again.
@peterzhuamazon @DandyDeveloper @bbarani 
Thank you

**Comment by josephteddick** [comment]
@TheAlgo @prudhvigodithi Thank you for the approval. I just did a helm template locally and all values checked out without error. Lmk if there is anything else you need.

**Review by prudhvigodithi — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Hey @josephteddick I have merged this PR, can you also please backport to 1.x?
Thank you

**Comment by josephteddick** [comment]
@prudhvigodithi Thanks for the merge! Just submitted the backport PR:
https://github.com/opensearch-project/helm-charts/pull/401

**Pull request merged**
