### PR TITLE
Provide a way to override the volumeClaimTemplate name

### PR DESCRIPTION
**Pull request by retoo**
### Description
The current volumeClaimTemplate name is rather long and leads to long PVC names. This PR introduces a new value `persistence.volumeClaimTemplateNameOverride`which allows the user to change the name. By default the value is not defined and the current name remains in use. 

 
### Issues Resolved
- #339
 
### Check List
- [x] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [ ] Helm chart version bumped
- [x] Helm chart `CHANGELOG.md` updated to reflect change

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Hi @retoo thanks for the contribution.
Is this something we can add for dashboards as well?

@TheAlgo @prudhvigodithi 

Thanks.

**Comment by retoo** [comment]
@peterzhuamazon yes, that should be possible. I try to look into it next weekend.

**Comment by peterzhuamazon** [comment]
Hi @DandyDeveloper @TheAlgo @prudhvigodithi please take a look and review.

Thanks.

**Review by DandyDeveloper — CHANGES_REQUESTED** [review]
Would it not be more ideal to instead implement a method for overwriting the entire volumeClaimTemplate? This seems like overload just for a name.

```
volumeClaimTemplates:
{{- range .Values.persistence.volumeClaimTemplates }}
- {{ toYaml (tpl .name $root) }} 
{{- end }}
```

Then in values:

```
persistence:
  volumeClaimTemplates:
    - name: {{ include "xyz.123" . }} 
       ...
 ```

Having an explicit override just for a name feels like bloat. 

With this you also give people the chance to add new volumes if they want for plugins / certs / whatever they want, which they can consume with initContainers. 

It's above and beyond the scope of your specific need, but I think we might as well at least implement something others can use rather than this niche use case described.

**Comment by prudhvigodithi** [comment]
Hey @retoo can you please check @DandyDeveloper comment and see if that is a valid scenario ?
Thank you

**Comment by prudhvigodithi** [comment]
Hey @retoo closing this, please re-open if required.
Thank you

**Pull request closed without merging**
