### PR TITLE
Allow passing in custom pod anti-affinity, as well as pod affinity

### PR DESCRIPTION
**Pull request by emmahsax**
### Description

This change allows people to pass in both pod affinity as well as custom pod anti-affinity (which will ignore the default `hard` and `soft` anti-affinity currently present in this helm chart).

To use the `customAntiAffinity`, `antiAffinity` must be set to `custom`, otherwise the default `soft` affinity will be used. If `antiAffinity` is set to `custom`, but nothing is specified in `customAntiAffinity`, then `{}` will be used for anti-affinity.
 
### Issues Resolved

This change will resolve https://github.com/opensearch-project/helm-charts/issues/397.
 
### Check List
- [x] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [x] Helm chart version bumped
- [x] Helm chart `CHANGELOG.md` updated to reflect change

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by emmahsax** [comment]
I'm not sure if I'm supposed to manually update the `CHANGELOG.md`, or if that's auto-generated. If it needs to be manual, let me know and I can update that.

**Comment by prudhvigodithi** [comment]
Hey @emmahsax, apologies for the delay, yes the changelog needs to be updated? Here is the sample merged Pull request https://github.com/opensearch-project/helm-charts/pull/482/files.

**Comment by emmahsax** [comment]
@prudhvigodithi Thanks. The Changelog is updated. I also synced my branch with the latest from `main` so that it updates to a newer version.

**Comment by prudhvigodithi** [comment]
Thanks @emmahsax, Since this is a not the OpenSerach version upgrade can you please change this to `2.17.1` (I will try to document this versioning in the contribution guidelines as well). Also please update the `[Unreleased]`  section in the changelog file, example https://github.com/opensearch-project/helm-charts/pull/506/files.

**Comment by emmahsax** [comment]
@prudhvigodithi Thanks! Complete.

**Comment by prudhvigodithi** [comment]
LGTM. @TheAlgo @peterzhuamazon can you please check?

**Review by prudhvigodithi — APPROVED** [review]

**Pull request merged**
