### PR TITLE
Add a simple cluster health test to CI

### PR DESCRIPTION
**Pull request by smlx**
### Description
This CI check should avoid bugs like those in #54 and #68.

~This PR is a draft as it depends on #37.~ That PR was merged.
 
### Issues Resolved
n/a
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by TheAlgo** [comment]
@smlx This is a good one. Do you have any rough ETA on this?

**Comment by smlx** [comment]
Yep, once #37 is in I'll rebase and it should be ready to go.

**Review by DandyDeveloper — COMMENTED** [review]
Great idea, good execution. 

However, for people who use tests in their CI workflows, they may define different credentials. 

Is there anywhere we can pull the `admin:admin` from in the values? @smlx

**Comment by smlx** [comment]
hmm. good point. I'll see if there is some way to do that.

**Comment by peterzhuamazon** [comment]
Asking again to see if @smlx has any updates.

**Comment by peterzhuamazon** [comment]
Any updates? @smlx 
Thanks.

**Comment by smlx** [comment]
Sorry I haven't had time to work on this. If anyone wants to take over please feel free, otherwise it might be a little while before I can get back to it.

**Comment by peterzhuamazon** [comment]
> Sorry I haven't had time to work on this. If anyone wants to take over please feel free, otherwise it might be a little while before I can get back to it.

Sure, thanks.

**Comment by prudhvigodithi** [comment]
Hey just checking back, do we still need this PR ?
@smlx @TheAlgo @DandyDeveloper @peterzhuamazon

**Comment by TheAlgo** [comment]
@smlx Any plans on this or we can close it for now?

**Pull request closed without merging**
