### PR TITLE
Change helm notes as the pod label key has changed

### PR DESCRIPTION
**Pull request by davidshtian**
### Description
Change helm notes as the pod label key has changed.
 
### Issues Resolved
Label Fix.
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by TheAlgo** [comment]
Hi @davidshtian , Can you create an issue for this, also please bump the chart and add the CHANGELOG. Thanks

**Comment by davidshtian** [comment]
> Hi @davidshtian , Can you create an issue for this, also please bump the chart and add the CHANGELOG. Thanks

Thanks for the guidance~ Please refer to the new created issue https://github.com/opensearch-project/helm-charts/issues/150, and I've also added CHANGELOG. Thanks~

**Comment by TheAlgo** [comment]
> > Hi @davidshtian , Can you create an issue for this, also please bump the chart and add the CHANGELOG. Thanks
> 
> Thanks for the guidance~ Please refer to the new created issue #150, and I've also added CHANGELOG. Thanks~

Can you also bump the chart version according to [semantic versioning](https://semver.org/spec/v2.0.0.html). Also you need to sign off the commit for DCO to pass on the PR .thanks

**Review by DandyDeveloper — APPROVED** [review]
Looks good.

Doesn't need a version bump so the CI related stuff can be ignored.

**Review by TheAlgo — CHANGES_REQUESTED** [review]
@davidshtian Can you please sign off your commit?

**Comment by peterzhuamazon** [comment]
Hi @davidshtian 
1. Please sign off your commit for DCO.
2. Bump charts version
3. Update changelog on the right place by adding a new section with the changed version number, not just simply adding to the changed section.
Thanks.

**Comment by peterzhuamazon** [comment]
Hi @davidshtian please pull from origin/main as your fork is not getting the latest versions, thus conflict.

Plus, you need to move your changelog section below `Unreleased`, see #152.

Thanks.

**Review by peterzhuamazon — APPROVED** [review]
Thanks.

**Pull request merged**
