### PR TITLE
Update helm opensearch version

### LINKED ISSUE #151: [Enhancement][OpenSearch/OpenSearch Dashboards] Make 1.2 as default image for opensearch helm charts
**Is your feature request related to a problem? Please describe.**
Plans for moving the default App Version of charts to use the latest OpenSearch version.

**Describe the solution you'd like**
Change [this](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/Chart.yaml#L24) to `1.2`

**Describe alternatives you've considered**
N/A

**Additional context**
It has been close to a week for the launch of OpenSearch 1.2. It will be great to switch the default version of the charts to `1.2`

### PR DESCRIPTION
**Pull request by derek-diaz**
### Description
Update `appVersion` to 1.2.0 
 
### Issues Resolved
#151 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by TheAlgo** [comment]
Hi @derek-diaz 

Thanks for making the PR. Can you bump the version and add CHANGELOG for the PR.
Follow the PR #149 to get an idea on what needs to be done.

**Comment by derek-diaz** [comment]
> 

Would this considered to be a Major, Minor or Patch release?

**Comment by TheAlgo** [comment]
> > @TheAlgo
> 
> Would this considered to be a Major, Minor or Patch release?

Patch release

**Comment by derek-diaz** [comment]
@TheAlgo Alright I think everything should be good now. Do let me know if I missed anything!

**Comment by peterzhuamazon** [comment]
Hi @derek-diaz strange that DCO does not pass can you rebase and push as one commit again?
Thanks.

**Pull request closed without merging**
