### PR TITLE
[Backport 1.x] Allow user-defined labels on pvcs

### LINKED ISSUE #554: [Enhancement][opensearch] Allow user-defined labels on pvcs
**Is your feature request related to a problem? Please describe.**
Our PVCs get backuped based on a policy defined in the PVC label. However it's currently not possible to define additional labels for the PVC (instead the global labels are applied if .Values.persistence.labels.enabled is true). 
**Describe the solution you'd like**
I'd like to define additional labels that are added besides the global labels. 

**Describe alternatives you've considered**
I don't see another way of doing it. 

**Additional context**
-

### PR DESCRIPTION
**Pull request by simonstumpf**
### Description
[Backport 1.x] Add support for user-defined labels on PVCs.
 
### Issues Resolved
Closes #554 
Backport #591
 
### Check List
- [x] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [ ] Helm chart version bumped
- [ ] Helm chart `CHANGELOG.md` updated to reflect change

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Thanks @simonstumpf, backport of https://github.com/opensearch-project/helm-charts/pull/591.
Adding @peterzhuamazon

**Review by prudhvigodithi — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
@simonstumpf can you please fix the failing CI's?
Thanks

**Comment by peterzhuamazon** [comment]
Not sure why is the failure tho, pinging @simonstumpf 
```

Installing chart with values file 'charts/opensearch/ci/ci-rbac-enabled-values.yaml'...

Creating namespace 'opensearch-wh6i31dni7'...
>>> kubectl create namespace opensearch-wh6i31dni7
namespace/opensearch-wh6i31dni7 created
>>> helm install opensearch-wh6i31dni7 charts/opensearch --namespace opensearch-wh6i31dni7 --wait --values charts/opensearch/ci/ci-rbac-enabled-values.yaml --timeout 1000s
Error: The operation was canceled.

```

Thanks.

**Comment by peterzhuamazon** [comment]
I am fixing this and merging.

**Pull request merged**
