### PR TITLE
[Backport 1.x] Add Service Monitor Resource

### PR DESCRIPTION
**Pull request by VILJkid**
### Description
It would add a prometheus serviceMonitor resource.

 
### Check List
- [x] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [x] Helm chart version bumped
- [x] Helm chart `CHANGELOG.md` updated to reflect change

PR sponsored by _[Obmondo](https://obmondo.com)_

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Thanks @VILJkid should we wait until this fix is pushed https://github.com/opensearch-project/helm-charts/issues/579#issuecomment-2306751619 ?
 @getsaurabh02 @peterzhuamazon

**Comment by VILJkid** [comment]
Thanks for the update, @prudhvigodithi!
I'll keep an eye on that, and update this PR accordingly.

**Review by peterzhuamazon — CHANGES_REQUESTED** [review]
Block until the bug is resolved on original main branch in case it get merged now.
* https://github.com/opensearch-project/helm-charts/issues/579

Thanks.

**Comment by peterzhuamazon** [comment]
Pending fix:
* https://github.com/opensearch-project/helm-charts/pull/581

**Comment by peterzhuamazon** [comment]
> Pending fix:
> 
>     * [[Fix] OpenSearch and OpenSearch Dashboards Service Monitor Bug #581](https://github.com/opensearch-project/helm-charts/pull/581)

Since this is merged now would you mind update this PR to include above changes?
Thanks @VILJkid !

**Comment by VILJkid** [comment]
Thanks @peterzhuamazon, I'll update this PR with the changes shortly.

**Comment by VILJkid** [comment]
@peterzhuamazon, kindly review the changes and let me know if it needs any improvement.
Thanks!

**Comment by peterzhuamazon** [comment]
Thanks @VILJkid , adding @prudhvigodithi to take a second pass.

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Waiting for @prudhvigodithi to give a second approval.

Thanks.

**Comment by prudhvigodithi** [comment]
There is a new bug created https://github.com/opensearch-project/helm-charts/issues/588, @VILJkid can you please take a look before we merge this?
Thank you

**Review by peterzhuamazon — CHANGES_REQUESTED** [review]
Block again due to new bug seen in here:
* https://github.com/opensearch-project/helm-charts/issues/588

**Comment by VILJkid** [comment]
Thanks @prudhvigodithi, @peterzhuamazon for highlighting the issue.
Here's the fix PR: https://github.com/opensearch-project/helm-charts/pull/589
Let me know if it needs any improvements.

**Comment by peterzhuamazon** [comment]
> Thanks @prudhvigodithi, @peterzhuamazon for highlighting the issue. Here's the fix PR: #589 Let me know if it needs any improvements.

Thanks @VILJkid I have merged that PR now.
Please go ahead and backport the changes here as well.

Thanks!

**Review by peterzhuamazon — COMMENTED** [review]
Thanks @VILJkid !

**Review by peterzhuamazon — APPROVED** [review]

**Pull request merged**
