### PR TITLE
Add annotations on headless service

### PR DESCRIPTION
**Pull request by DocMarten**
### Description
Required to set needed annotations on headless service for external-dns.
see: https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/hostport.md

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Hi @DocMarten could you open an issue about it and link to this PR?
Also please follow #152 as an example to update version, changelog, and sign DCO.

Thanks.

**Comment by peterzhuamazon** [comment]
Hi @DocMarten can you take 1.5.10 version number, as 1.5.8/1.5.9 already taken and awaiting for approval.
If you check https://github.com/opensearch-project/helm-charts/pulls you will see the queue.

Thanks.

**Comment by peterzhuamazon** [comment]
Also, since you are adding new entries in configurations, could you update the readme here as well?
https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/README.md#configuration

Thanks.

**Comment by peterzhuamazon** [comment]
Hi @DandyDeveloper @TheAlgo please take a look at this.

Thanks.

**Comment by peterzhuamazon** [comment]
Hi @DocMarten lint checker did not pass
```
Error:  templates/service.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 13: did not find expected key
```

Can you check the error and fix it?
Thanks.

**Comment by peterzhuamazon** [comment]
Hi @DocMarten it is still showing the exact same error.
@DandyDeveloper @TheAlgo can you take a look at this?
Thanks.

**Comment by peterzhuamazon** [comment]
After linting I found this error:
```
✖ missed comma between flow collection entries at line 7, column 7:
        {{- include "opensearch.labels" .  ...
          ^
```

**Comment by DocMarten** [comment]
@peterzhuamazon ok, I found the cause. Sorry for the inconvenience.

**Comment by TheAlgo** [comment]
> @peterzhuamazon ok, I found the cause. Sorry for the inconvenience.

Thanks @DocMarten . The lint is passing now. It was a small typo kinda issue. 😅

**Comment by peterzhuamazon** [comment]
@DandyDeveloper @TheAlgo please take a look as the PR is now clear of checks.
Thanks.

**Review by TheAlgo — APPROVED** [review]
LGTM!

**Comment by TheAlgo** [comment]
@DandyDeveloper Please review this when free. Thanks

**Review by DandyDeveloper — COMMENTED** [review]
@TheAlgo Do we not think `annotationsHeadless` is not a good idea? 

I think we should be open to adding stuff to the headless service so;

```yaml
service:
  headless:
    annotations: {}
```

Is better imo.

**Comment by TheAlgo** [comment]
> @TheAlgo Do we not think `annotationsHeadless` is not a good idea?
> 
> I think we should be open to adding stuff to the headless service so;
> 
> ```yaml
> service:
>   headless:
>     annotations: {}
> ```
> 
> Is better imo.

@DandyDeveloper Yes I second that. This is a better approach. I went with the same flow as we had for labels in headless `labelsHeadless` but this looks more clean and tidy.

**Comment by peterzhuamazon** [comment]
@DocMarten could you check the comments above?
Thanks.

**Comment by peterzhuamazon** [comment]
Remove tag from this PR as we will dynamically assign version later.

**Comment by DocMarten** [comment]
@peterzhuamazon & @DandyDeveloper 
I can change that but there are other values, which are not consistent after that.

for example:
```
service:
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
```

```
service:
    loadBalancer:
      ip: ""
      sourceRanges: []
```

What about `service.headlessLabels`?

```
headless:
    labels: {}
    annotations: {}
```

**Comment by TheAlgo** [comment]
> service.headlessLabels

I cannot think of any bad UX with `service.headlessLabels`. @DandyDeveloper @peterzhuamazon thoughts?

**Comment by DandyDeveloper** [comment]
@DocMarten @TheAlgo Other values should be updated to reflect my suggested changes IMO. 

But right now, those could impact existing users and weren't picked up when this chart was created. 

I think we should get things right from the get go on newer values being introduced. 

I can be overruled, but I stand by using this format;

```yaml
service:
  headless:
    annotations: {}
```

**Comment by peterzhuamazon** [comment]
Hi @DandyDeveloper @TheAlgo seems like this PR is stalled for a while.
Anything we can put to get it going?

Thanks.

**Comment by TheAlgo** [comment]
> @DandyDeveloper @TheAlgo It's up to you. The current version is:
> 
> ```
> service:
>   headless:
>     annotations: {}
> ```

I am good with this approach. @DandyDeveloper I guess the current version is according to your recommendation.

**Comment by peterzhuamazon** [comment]
Since there is yet relies from @DandyDeveloper can @smlx or @mprimeaux help take a look at this?
Thanks.

**Review by DandyDeveloper — APPROVED** [review]
I didn't realise this needed approval again. Sorry. 

Yes, this works, it'd be nice to update the `headlessLabels` as well and note the breaking change in a separate PR.

**Pull request merged**
