### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by viceice**
### Description
Just a small typo
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by TheAlgo** [comment]
@viceice could you please sign off the commit ?

**Review by TheAlgo — CHANGES_REQUESTED** [review]
@viceice could you please sign off the commit ?

**Comment by viceice** [comment]
Yes, sorry. Isn't possible via github UI 😕

**Review by TheAlgo — APPROVED** [review]

**Review by DandyDeveloper — APPROVED** [review]

**Comment by TheAlgo** [comment]
@DandyDeveloper @peterzhuamazon @mprimeaux  I believe we can ignore CI failures here. Opinions?

**Comment by mprimeaux** [comment]
@TheAlgo I believe that @smlx views any change to a chart, including documentation, as requiring a version increment. In lieu of the chart testing failure, so do the maintainers and related community of the chart testing logic.

As such, I suspect a patch bump is required.

**Comment by TheAlgo** [comment]
> @TheAlgo I believe that @smlx views any change to a chart, including documentation, as requiring a version increment. In lieu of the chart testing failure, so do the maintainers and related community of the chart testing logic. I'm of the same view.
> 
> As such, I suspect patch bump is required. This would also require an update to the related CHANGELOG.

Agree but shouldn't we relax the CI failures for README changes 

@DandyDeveloper @smlx @mprimeaux @peterzhuamazon

**Comment by mprimeaux** [comment]
Please see [this](https://github.com/opensearch-project/helm-charts/pull/81#discussion_r720671528) conversation that we had on this very point.

The README is in scope as a change to the chart and thus subject to linting rules.

I don't believe this view has changed but you might want to check with @smlx on it.

**Comment by smlx** [comment]
I'm not a maintainer on this repo so feel free to ignore me, but IMO rapid releases are a feature and get the latest fixes to users ASAP. Could a maintainer push a patch bump on this branch to get CI green?

**Comment by peterzhuamazon** [comment]
@viceice I resolved the conflicts for you, please remember you need to pull from main, change version number, and update changelog next time when you PR.

Thanks.

**Pull request merged**
