### PR TITLE
Use correct serviceAccountName in statefulset template

### PR DESCRIPTION
**Pull request by UXabre**
Signed-off-by: Arend Lapere <arend.lapere@gmail.com>

### Description
Use correct serviceAccountName in statefulset template.
 
### Issues Resolved
https://github.com/opensearch-project/helm-charts/issues/202
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by TheAlgo — COMMENTED** [review]
@UXabre   Would you mind creating an issue for the same. Also please bump this chart version to `1.7.2`. We have a PR for `1.7.1`, apologies for it. Refer contribution [guidelines](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md) for more details.

**Comment by UXabre** [comment]
Hi @TheAlgo , Sorry, I had linked it but the title in the description was wrong, fixed that. Also bumped the version :-)
Thanks for your input

**Comment by UXabre** [comment]
oops, I had commited using a different mail address

**Comment by peterzhuamazon** [comment]
@DandyDeveloper @TheAlgo please take a look and review this PR.
I will take over the task if version number needs to be tweaked later.
Thanks.

**Review by TheAlgo — APPROVED** [review]
LGTM!

**Review by DandyDeveloper — APPROVED** [review]
Good spot.

**Pull request merged**
