### PR TITLE
Mount volume `security-config-complete` if `Values.securityConfig.config.securityConfigSecret` is passed

### PR DESCRIPTION
**Pull request by JunaidChaudry**
Fixed `securityConfig` mount. 
The `security-config-complete` was not mounting when an external secret was passed using `securityConfig.config.securityConfigSecret`

### Description
According to the docs, a user should be able to pass in a pre-created secret under `Values.securityConfig.config.securityConfigSecret`, which can be used to provide securityConfig config files. However, a bug in the statefulset.yaml was skipping the volume mount for this use case, even though the volume was being created by it. 
 
### Issues Resolved
[#210](https://github.com/opensearch-project/helm-charts/issues/210) 

### Check List
- [ ] Commits are signed per the DCO using --signoff 
- [ ] CHANGELOG.md updated
- [ ] Chart Version updated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Hi @JunaidChaudry thanks for this would you mind create a simple issue and link to this PR?
It would be easier to track later on.

Thanks.

**Comment by peterzhuamazon** [comment]
Seems like you need to sign the DCO with `git commit --amend --no-edit -s`.

Also, please create a new section in CHANGELOG.md for `1.7.2` without using the `Unreleased` section.

You also need to scroll all the way in that file to upload the changelog commit diffs.

Thanks.

**Comment by JunaidChaudry** [comment]
All should be updated

**Comment by peterzhuamazon** [comment]
@DandyDeveloper @TheAlgo please take a look and review this PR.
Thanks.

**Review by DandyDeveloper — APPROVED** [review]
Good find.  Thank you.

**Comment by peterzhuamazon** [comment]
Please ignore the conflicts if it happens after we merge #203.
Once @TheAlgo also approve this I will fix the versions and conflicts to 1.7.3.
Thanks.

**Review by TheAlgo — COMMENTED** [review]
LGTM!

**Review by TheAlgo — APPROVED** [review]

**Pull request merged**
