### PR TITLE
Fix deprication warnings about node.roles. Now roles described as a list

### PR DESCRIPTION
**Pull request by Sebor**
Signed-off-by: Sebor <al.sprut@gmail.com>

### Description
Rework deprecated node roles definition. 
Now in `values.yaml` roles are described as a list and there are no any deprecation warnings in logs.
 
### Issues Resolved
- #122 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Sebor** [comment]
Hi @TheAlgo, @DandyDeveloper!
Do you have any questions about this PR?

**Review by peterzhuamazon — COMMENTED** [review]
I am ok with this change, just need one of @DandyDeveloper and @TheAlgo to approve.

**Review by DandyDeveloper — APPROVED** [review]
Good move.

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Thanks @Sebor

**Pull request merged**
