### PR TITLE
Fixed init resources bug

### PR DESCRIPTION
**Pull request by prudhvigodithi**
Signed-off-by: pgodithi <pgodithi@amazon.com>

### Description

1. Fix initResources bug, initResources mapped in values file should be able to now get added to OpenSearch statefulset
2. Added initResources to map the fsgroup-volume container.

 
### Issues Resolved
https://github.com/opensearch-project/helm-charts/issues/248
 
### Check List
- [x] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [x] Helm chart version bumped
- [x] Helm chart `CHANGELOG.md` updated to reflect change

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
@DandyDeveloper @TheAlgo @peterzhuamazon please review.

**Comment by prudhvigodithi** [comment]
Hey @DandyDeveloper and @TheAlgo, just checking back again, can you please review the PR?

**Comment by TheAlgo** [comment]
> Hey @DandyDeveloper and @TheAlgo, just checking back again, can you please review the PR?

I will review it by tomorrow EOD

**Review by TheAlgo — COMMENTED** [review]
LGTM. I have assigned it the number 1.11.1 so that #172 can go before this

**Comment by prudhvigodithi** [comment]
> LGTM. I have assigned it the number 1.11.1 so that #172 can go before this

Thanks, once merged I will update with the the changelog and chart.yaml file's.

**Comment by TheAlgo** [comment]
> > LGTM. I have assigned it the number 1.11.1 so that #172 can go before this
> 
> Thanks, once merged I will update with the the changelog and chart.yaml file's.

There are some good points raised by Scott on the PR. I will take a look at it in some time. Lets not block this till then

**Review by TheAlgo — APPROVED** [review]

**Review by peterzhuamazon — APPROVED** [review]

**Pull request merged**
