### PR TITLE
Use a per-install name for securityconfig secret

### PR DESCRIPTION
**Pull request by smlx**
### Description
Give the securityconfig secret an autogenerated unique name to
facilitate installing the chart multiple times in the same namespace.

This helps with the common case of sharing the securityconfig between
multiple instantiations of this chart to construct an Opensearch
cluster.
 
### Issues Resolved
Closes: #40 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by DandyDeveloper — COMMENTED** [review]
The problem with this is the previous implementation allowed someone to pass in their own `template/secret.yaml` in their child chart. 

This actually becomes more restrictive.

We should support both. Maybe with a `{{ default (printf "%s-securityconfig" include "opensearch.uname" . ) .Values.securityConfig.config.securityConfigSecret }}` in the statefulset references to the volume?

**Comment by smlx** [comment]
> The problem with this is the previous implementation allowed someone to pass in their own template/secret.yaml in their child chart.

Could you explain how this was supposed to work previously?

The volume bindings on the statefulset have conditionals like this, which is identical to the conditional on the creation of the `securityconfig` secret object:
```
{{- if and .Values.securityConfig.config.securityConfigSecret .Values.securityConfig.config.data }}
```
This means that they wouldn't have been able to supply an external secret name and have the statefulset use it with this mechanism.

I think you can still use an external secret by specifying `extraVolumes` + `extraVolumeMounts`?

**Comment by DandyDeveloper** [comment]
@smlx I'm going to say this wasn't ported very well from the original. Those conditions are a bug, but I think your change still introduces more restrictions.

It'd be more logical to just remove the verbose (and unnecessary) conditions you've outlined.

**Comment by smlx** [comment]
Ok, so what if we changed it to have this kind of logic:

* if you define anything under `data`, the chart will automatically create a secret and mount it (this is what the PR does now)
* if you define `securityConfigSecret`, the chart will assume this secret is created externally and try to mount it.
* it is an error to define both `data` and `securityConfigSecret`

Does that satisfy all the use cases? I'll obviously add some comments explaining how this works.

**Comment by DandyDeveloper** [comment]
@smlx Perfect middle ground. Agreed.

**Comment by TheAlgo** [comment]
> Ok, so what if we changed it to have this kind of logic:
> 
> * if you define anything under `data`, the chart will automatically create a secret and mount it (this is what the PR does now)
> * if you define `securityConfigSecret`, the chart will assume this secret is created externally and try to mount it.
> * it is an error to define both `data` and `securityConfigSecret`
> 
> Does that satisfy all the use cases? I'll obviously add some comments explaining how this works.

@smlx Can we add this explanation in the README for OpenSearch chart. It will be great to avoid any confusions for users.

**Comment by peterzhuamazon** [comment]
Any progress on this PR @smlx ?

**Comment by peterzhuamazon** [comment]
Sorry about my misclick on closing the PR, open again.
Hi @DandyDeveloper @TheAlgo can you please take a look and approve?
Thanks.

**Comment by smlx** [comment]
I've rebased and bumped the version.

**Comment by TheAlgo** [comment]
> > Ok, so what if we changed it to have this kind of logic:
> > 
> > * if you define anything under `data`, the chart will automatically create a secret and mount it (this is what the PR does now)
> > * if you define `securityConfigSecret`, the chart will assume this secret is created externally and try to mount it.
> > * it is an error to define both `data` and `securityConfigSecret`
> > 
> > Does that satisfy all the use cases? I'll obviously add some comments explaining how this works.
> 
> @smlx Can we add this explanation in the README for OpenSearch chart. It will be great to avoid any confusions for users.

@smlx Can we add it in the README as well?

**Comment by smlx** [comment]
@TheAlgo ok, added a line to the README.

**Review by TheAlgo — COMMENTED** [review]
@peterzhuamazon @mprimeaux @smlx @DandyDeveloper Should be make this `1.1.0`?

**Comment by mprimeaux** [comment]
@peterzhuamazon Yes to `1.1.0` as this introduces a new non-breaking feature and therefore mandates a minor version number increment.

**Comment by smlx** [comment]
OK, changed version to `1.1.0`.

**Comment by DandyDeveloper** [comment]
@smlx I think that's the best way to address this.

**Pull request merged**
