### PR TITLE
fix(deployment): typo regarding topologySpreadConstraints

### PR DESCRIPTION
**Pull request by cpockrandt**
### Description
There's a bug introduced by a typo in the latest helm chart release.
 
### Issues Resolved
[List any issues this PR will resolve. You should likely open an issue if one does not already exist.]
 
### Check List
- [x] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [x] Helm chart version bumped
- [x] Helm chart `CHANGELOG.md` updated to reflect change

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cpockrandt** [comment]
Could someone take a look at this PR and review it please? :)

**Comment by dazoakley** [comment]
Hi folks, any chance this could be looked at, at the moment the dashboards chart is completely broken. 

We'd like to update the chart we're using and include TCS's... :smile:

**Comment by gaiksaya** [comment]
> Hi folks, any chance this could be looked at, at the moment the dashboards chart is completely broken.
> 
> We'd like to update the chart we're using and include TSC's... 😄

Looks like there are conflicts in the files. Can you please rebase and resolve the conflicts?
Thanks!

**Comment by peterzhuamazon** [comment]
I will update this PR and review.

**Review by prudhvigodithi — APPROVED** [review]

**Review by gaiksaya — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Doesnt seem it requires any backports.
Thanks @cpockrandt .

**Pull request merged**
