### PR TITLE
Certs faq

### PR DESCRIPTION
**Pull request by NybbleHub**
### Description
Add notes in README to solve the `Demo certificates found but plugins.security.allow_unsafe_democertificates is set to false.` error when custom certifcates are used.
 
### Issues Resolved
[Issue 154](https://github.com/opensearch-project/helm-charts/issues/154)
 
### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by TheAlgo** [comment]
@peterzhuamazon @DandyDeveloper How about if we add labels to the PR to do a time-boxed reservation of a chart version to resolve issues?

**Review by TheAlgo — COMMENTED** [review]
Can we move this README to the inner [README](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/README.md) for OpenSearch. 

Also @NybbleHub can you sign off your commits?

**Review by DandyDeveloper — APPROVED** [review]
I thought Opensearch was supposed to do this when certain configuration options were applied?

**Comment by DandyDeveloper** [comment]
@TheAlgo Can you expand on your statement? Can you give an example on what it solves? I don't fully understand.

**Comment by TheAlgo** [comment]
> @TheAlgo Can you expand on your statement? Can you give an example on what it solves? I don't fully understand.

For this PR if we add a label `1.5.8` then the next PR that goes in , can have the chart version `1.5.9`, when the compatible PR comes we can assign labels to it. This way contributors will not get confused.

**Comment by NybbleHub** [comment]
> Also @NybbleHub can you sign off your commits?

Sorry, it's the first time I made a pull request.

I commited again on my branch with `git commit --amend --signoff` and then pushed again. What I need to do now ? 

Thanks !

**Comment by TheAlgo** [comment]
> > Also @NybbleHub can you sign off your commits?
> 
> Sorry, it was the first time I made a pull request.
> 
> I commited again on my branch with `git commit --amend --signoff` and then pushed again. What I need to do now ?
> 
> Thanks !

Not a problem. @NybbleHub You will have to sign off the previous commits as well to pass these checks

**Comment by NybbleHub** [comment]
@TheAlgo is it good now ?

**Comment by peterzhuamazon** [comment]
@NybbleHub 
```
  9171c327308f3e32241410adc4fc9c8f484c68a6    Expected "sebastien.lehuede <sebastien.lehuede@nybble.bzh>", but got "Your Name Sébastien Lehuédé <sebastien.lehuede@nybble.bzh>".
```

Seems like you mistakenly put `Your Name` as part of your name.
Could you fix that @NybbleHub thanks.

**Comment by NybbleHub** [comment]
> @NybbleHub
> 
> ```
>   9171c327308f3e32241410adc4fc9c8f484c68a6    Expected "sebastien.lehuede <sebastien.lehuede@nybble.bzh>", but got "Your Name Sébastien Lehuédé <sebastien.lehuede@nybble.bzh>".
> ```
> 
> Seems like you mistakenly put `Your Name` as part of your name. Could you fix that @NybbleHub thanks.

Ok, finaly this should be good

**Comment by peterzhuamazon** [comment]
A lot of conflicts in files @NybbleHub

**Comment by peterzhuamazon** [comment]
Hi @NybbleHub could you fix the conflicts?
Thanks.

**Comment by peterzhuamazon** [comment]
Since there is no response from @NybbleHub for some time I will move it to the end of the queue with `1,5,10` for now.

**Comment by NybbleHub** [comment]
Hi !

Sorry, christmas holidays. I resolved the conflict, can you check if it's good now ?

**Comment by peterzhuamazon** [comment]
Hi @NybbleHub please follow #152 as an example:
1. Sign DCO.
2. Bump version `1.5.10`.
3. Update changelog.

Thanks.

**Comment by peterzhuamazon** [comment]
Remove tag from this PR as it has no update for a while.

**Comment by peterzhuamazon** [comment]
I will try to fix this from my side.

**Review by peterzhuamazon — APPROVED** [review]

**Review by DandyDeveloper — APPROVED** [review]

**Pull request merged**
