### PR TITLE
added description for lifecycle parameter

### PR DESCRIPTION
**Pull request by premkirank**
### Description
Added a ```description``` for the lifecycle parameter in README
 
### Issues Resolved
Fixes https://github.com/opensearch-project/helm-charts/issues/459
 
### Check List
- [x] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [x] Helm chart version bumped
- [x] Helm chart `CHANGELOG.md` updated to reflect change

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by afrodidact — COMMENTED** [review]
Looks good!

**Review by TheAlgo — CHANGES_REQUESTED** [review]
@premkirank  Thanks for your contribution. Changes looks good to me. Can you rebase with latest version of the chart. We released a new version yesterday so maybe you can build on top of that. Thanks

P:S There is a PR with similar changes raised 3 weeks ago so we need to wait on that PR. If that contributor can rebase we need to merge that change as that was raised first :)

**Comment by prudhvigodithi** [comment]
@premkirank can you please take a look at this [comment](https://github.com/opensearch-project/helm-charts/pull/482#pullrequestreview-1682150565). Thanks

**Comment by premkirank** [comment]
> @premkirank can you please take a look at this [comment](https://github.com/opensearch-project/helm-charts/pull/482#pullrequestreview-1682150565). Thanks

@prudhvigodithi I had rebased my PR and requested a review again. Is there anything else that I have missed?

**Comment by prudhvigodithi** [comment]
Thanks, the CI tests fail can you please take care of it @premkirank ?

**Comment by premkirank** [comment]
@prudhvigodithi I am not able to understand why the tests are failing. Please help here.

**Review by TheAlgo — COMMENTED** [review]
@premkirank You have updated the `appVersion` to `2.12` and we don't have a version of OpenSearch yet. Can you revert this to `2.11`. You only need to update chart version and not app version.

**Comment by premkirank** [comment]
> @premkirank You have updated the `appVersion` to `2.12` and we don't have a version of OpenSearch yet. Can you revert this to `2.11`. You only need to update chart version and not app version.

@TheAlgo @prudhvigodithi have reverted the app version

**Review by TheAlgo — APPROVED** [review]
LGTM!

**Comment by TheAlgo** [comment]
@prudhvigodithi Please do have a look when free. Thanks

**Comment by prudhvigodithi** [comment]
Thanks @TheAlgo, @premkirank can you please backport this to 1.x branch as well? this is for the OpenSearch 1.x series.
Thank you

**Comment by premkirank** [comment]
> Thanks @TheAlgo, @premkirank can you please backport this to 1.x branch as well? this is for the OpenSearch 1.x series. Thank you

@prudhvigodithi Here is the backport PR - https://github.com/opensearch-project/helm-charts/pull/491

**Pull request merged**
