### PR TITLE
Correct defaults for opensearchJavaOpts in README 

### PR DESCRIPTION
**Pull request by jeidsath**
### Description
Correct defaults for opensearchJavaOpts in README 
 
### Issues Resolved
https://github.com/opensearch-project/helm-charts/issues/566
 
### Check List
- [x] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [x] Helm chart version bumped
- [x] Helm chart `CHANGELOG.md` updated to reflect change

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Hi @TheAlgo @prudhvigodithi can we confirm this is the case?
I do remember initially we have it as 1g/1g?

Thanks.

**Comment by jeidsath** [comment]
Hey @peterzhuamazon, 

The current default setting can be seen on [line 146](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/values.yaml#L146) of values.yaml

We only noticed this because our running cluster did not match the documented default memory usage.

Rather than changing the README, it would also be an option to adjust values.yaml to match the documented default. But as this would silently double memory usage for anyone automatically upgrading their clusters (with flux, etc.), the README change seemed like a simpler option.

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Thanks @jeidsath , merged.
Are you able to backport this to 1.x branch?

Thanks.

**Comment by peterzhuamazon** [comment]
nvm, I backported: https://github.com/opensearch-project/helm-charts/pull/571

Thanks.

**Pull request merged**
