### PR TITLE
Remove stale README for OpenSearch Helm Chart

### LINKED ISSUE #56: [Clean up][OpenSearch]
**Describe the bug**
A stale readme is present [here](https://github.com/opensearch-project/helm-charts/blob/main/charts/README.md) which is not required as we already have chart level [README](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/README.md)

**To Reproduce**
N/A

**Expected behavior**
Stale README should be removed

**Chart Name**
OpenSearch

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
N/A

**Additional context**

### PR DESCRIPTION
**Pull request by TheAlgo**
Signed-off-by: TheAlgo <dhirajjain0@gmail.com>

### Description
Remove stale [README](https://github.com/opensearch-project/helm-charts/blob/main/charts/README.md)
 
### Issues Resolved
#56 
 
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peterzhuamazon — APPROVED** [review]

**Comment by TheAlgo** [comment]
@DandyDeveloper Have a look when free. Thanks

**Review by DandyDeveloper — APPROVED** [review]
Pendantic opinion: Can we just have this top level just have things like; 

* Information on adding the repo
* Hyperlinks to the chart level README

If not, LGTM!

**Comment by peterzhuamazon** [comment]
> Pendantic opinion: Can we just have this top level just have things like;
> 
>     * Information on adding the repo
> 
>     * Hyperlinks to the chart level README
> 
> 
> If not, LGTM!

I do think adding a hyperlink on top would help.

**Comment by TheAlgo** [comment]
@peterzhuamazon @DandyDeveloper We already have a high level [README.md](https://github.com/opensearch-project/helm-charts/blob/main/README.md) where we can add links to chart specific README. But again if you guys feel I can go ahead and make the change,

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon @DandyDeveloper We already have a high level [README.md](https://github.com/opensearch-project/helm-charts/blob/main/README.md) where we can add links to chart specific README. But again if you guys feel I can go ahead and make the change,

Lets add a simple link so users can be well informed on this. Thanks.

**Comment by mprimeaux** [comment]
@TheAlgo Seems we are all working on overlapping things. Would you mind reviewing PR #75?

**Comment by TheAlgo** [comment]
> @TheAlgo Seems we are all working on overlapping things. Would you mind reviewing PR #75?

Sure let me have a look at it.

**Comment by TheAlgo** [comment]
@peterzhuamazon I guess now we are good to merge this. I don't think #75 will get affected with it anyways.

**Pull request merged**
