### PR TITLE
Add support for pod topology spread constraints

### PR DESCRIPTION
**Pull request by mkhpalm**
Signed-off-by: Mike Palmer <mpalmer@terascope.io>

### Description

Add support for pod topology spread constraints

https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/

### CODE REVIEW

**Comment by TheAlgo** [comment]
@mkhpalm Would you mind creating an issue for this PR? Thanks

**Comment by mkhpalm** [comment]
> @mkhpalm Would you mind creating an issue for this PR? Thanks
> 
> P:S: Got through the contribution guidelines once. Looks like you need to bump chart version and add changelog

New issue: https://github.com/opensearch-project/helm-charts/issues/222

Also, I synced upstream, bumped the chart patch, and added a changelog.

**Comment by peterzhuamazon** [comment]
@DandyDeveloper @TheAlgo please review, I can fix up any version issues if any later.

**Review by TheAlgo — COMMENTED** [review]
LGTM.  Thanks a lot for taking it up.

Can you add some details in the [README ](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/README.md) of the chart so that it becomes easy for the people to use it. Thanks

**Comment by mkhpalm** [comment]
> LGTM. Thanks a lot for taking it up.
> 
> Can you add some details in the [README ](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/README.md) of the chart so that it becomes easy for the people to use it. Thanks
> 

Done, thanks

**Comment by peterzhuamazon** [comment]
@DandyDeveloper @TheAlgo please review again I will fix the conflicts later.

**Review by DandyDeveloper — APPROVED** [review]

**Review by TheAlgo — APPROVED** [review]
LGTM!

**Pull request merged**
