### PR TITLE
fix: Handle log4j2 not being yaml (#110)

### LINKED ISSUE #110: [BUG][opensearch] log4j2.properties in values.yaml does not work with toYaml in configmap.yaml
**Describe the bug**
In the current chart for `opensearch-dashboards` it is not possible to template `log4j2.properties` as the `configmap.yaml` expects input to _be_ in yaml.
log4j2.properties is not yaml but has a `key = value` structure.

This makes it not possible to override the log4j configuration with the current chart.

**To Reproduce**
1. Add helm repo
2. Edit `values.yaml` and add `log4j2.properties` to `config`
3. `helm install`
4. See error, which is that the file is created without line breaks, which renders it unusable.

This happens because the log4j2.properties is _not_ YAML, but rather `key = value`.
Any yaml multiline trick does not work.

Error message from pod:

```
2021-10-28 12:28:14,202 main ERROR Invalid status level specified: ERROR APPENDER.CONSOLE.TYPE = CONSOLE APPENDER.CONSOLE.NAME = CONSOLE APPENDER.CONSOLE.LAYOUT.TYPE. Defaulting to ERROR.
```

**Expected behavior**
log4j2.properties to be created in a proper format.

**Chart Name**
opensearch - configmap

https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/templates/configmap.yaml#L11 - `toYaml`

**Screenshots**

Example config in `values.yaml`

```yaml
config:
  log4j2.properties:
    status = error
    appender.console.type = Console
    appender.console.name = console
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n
    rootLogger.level = info
    rootLogger.appenderRef.console.ref = console
    logger.plugins.security.name = com.amazon.dlic.auth.http.jwt
    logger.plugins.security.level = trace
```

Output from `helm install`

```yaml
config:
  log4j2.properties: status = error appender.console.type = Console appender.console.name
    = console appender.console.layout.type = PatternLayout appender.console.layout.pattern
    = [%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n rootLogger.level = info
    rootLogger.appenderRef.console.ref = console logger.plugins.security.name = com.amazon.dlic.auth.http.jwt
    logger.plugins.security.level = trace
```

configmap:

```yaml
data:
  log4j2.properties: |
    status = error appender.console.type = Console appender.console.name = console appender.console.layout.type
      = PatternLayout appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}]
      [%node_name]%marker %m%n rootLogger.level = info rootLogger.appenderRef.console.ref
      = console logger.plugins.security.name = com.amazon.dlic.auth.http.jwt logger.plugins.security.level
      = trace
```

Resulting file:

```bash
$ k exec -ti opensearch-1 -- bash -c "cat config/log4j2.properties"
status = error appender.console.type = Console appender.console.name = console appender.console.layout.type
  = PatternLayout appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}]
  [%node_name]%marker %m%n rootLogger.level = info rootLogger.appenderRef.console.ref
  = console logger.plugins.security.name = com.amazon.dlic.auth.http.jwt logger.plugins.security.level
  = trace
```

**Host/Environment (please complete the following information):**
 - Helm Version: 3.7.0
 - Kubernetes Version: 1.21.2

**Additional context**
Workaround would probably be to create a separate configmap and reference, but using it in `values.config` should also work.

### PR DESCRIPTION
**Pull request by sastorsl**
Bump chart (#110)

Signed-off-by: Stein Arne Storslett <sastorsl@users.noreply.github.com>

### Description
Render `log4j2.properties` properly when added to `values.yaml` / `config`.
The current version does a `toYaml`, but log4j2 is `key = value` based and not yaml so without this PR log4j2 will not be rendered properly (see issue for details).

Maintainers may adjust the Chart version as needs be, ie. to align with other PR's but please contact me for any other changes.
 
### Issues Resolved
#110 
 
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Looks like version bump needs to be higher?

**Comment by DandyDeveloper** [comment]
@sastorsl Wouldn't this be better to just `tpl <Value> .` rather then this? The `toYaml` may be redundant.

**Comment by sastorsl** [comment]
> Looks like version bump needs to be higher?

A bit hard to determine from the outside, given that there are a few PR's, and thus conflicts.
@peterzhuamazon could a solution be that you in the team name a version number and I'll add it?

**Comment by TheAlgo** [comment]
Seeing the current scenario I feel we can start off with long lived release branches. If everyone is okay with it I can create one. We can have those branches merged to main after the patch is ready so one and so forth. 

Reference : #79

**Comment by sastorsl** [comment]
> @sastorsl Wouldn't this be better to just `tpl <Value> .` rather then this? The `toYaml` may be redundant.

@DandyDeveloper I was really trying to not change how the chart handled config files, trying to avoid those regressions...
The PR I submitted "only" changes the handling og `log4j2.properties` and thus does not change anything else.

[`tpl`](https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function) docs are quite terse, and I see that there has been some issues with regards to `tpl` and the use of `range`, i.e. https://github.com/helm/helm/issues/5979
I did a couple of tests and was at least not able to find a solution in a satisfactory time frame.

I would think (hope) that rewriting to use `tpl` could be in scope further down the road for somebody more well versed in it's use, and I hope that we can move forward with this PR as it stands.

**Comment by peterzhuamazon** [comment]
@sastorsl DCO check fail because pulling from main will not sign.
You need to sign again after pulling.

Thanks.

**Comment by sastorsl** [comment]
@peterzhuamazon I've resolved the DCO-issue now.

**Comment by peterzhuamazon** [comment]
For some reason it is keep pointing to `5a963b9daeaf3d89f5856366df1f6e8fc730e4ba`

**Comment by sastorsl** [comment]
I'm removing this PR and replacing it with a clean one (#123).
Sorry for the mess...

**Pull request closed without merging**
