### PR TITLE
Remove deprecated discovery.zen from documentation. Closes #141.

### LINKED ISSUE #141: [BUG][opensearch] Discovery documentation deprecated
**Describe the bug**
[values.yaml](https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/values.yaml) and README, etc reference the deprecated (since 7.x) Zen discovery type.

**To Reproduce**

Since upstream version 7.0 the Zen discovery type has been deprecated.
I.e. the `discovery.zen.minimum_master_nodes` setting is allowed but ignored.

Ref upstream [elasticsearch 7.0 breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#breaking_70_discovery_changes)

**Expected behavior**
Readme / values, etc should reflect the current settings for cluster formation and discovery.

**Chart Name**
Specify the Chart which is affected?

* `opensearch`

**Screenshots**
Ref upstream [elasticsearch 7.0 breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#breaking_70_discovery_changes)

**Host/Environment (please complete the following information):**
 - Helm Version: [e.g. 3.7.0]
 - Kubernetes Version: [e.g. 1.22.3]

**Additional context**
On cluster **bootstrap** you set the following on master-eligible nodes.
This can (and should) be removed after the cluster has formed.

```yaml
cluster.initial_master_nodes:
  - master-a
  - master-b
  - master-c
```

All other nodes configure seed nodes - including nodes which are added at a later time:

```yaml
discovery.seed_hosts:
  - master-a
  - master-b
  - master-c
```

### PR DESCRIPTION
**Pull request by sastorsl**
### Description
Remove references to the deprecated zen.discovery.
Update documentation and values examples.

INFO: Discovery for "single-node" was already mentioned in the docs, and general discovery is already managed automatically in the statefulset with discovery.seed_hosts.

According to the CONTRIBUTING.md the helm chart should **not** be bumped on documentation changes only.
 
### Issues Resolved
#141 
 
### Check List
- [X] Commits are signed per the DCO using --signoff

For any changes to files within Helm chart directories:
- [X] Helm chart version bumped
- [X] Helm chart `CHANGELOG.md` updated to reflect change

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/helm-charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by sastorsl** [comment]
I see now that the checks fails due to missing chart bumps, so it's good if the team have a look at this and let me know if the chart should be bumped or not (ref "documentation only").

**Comment by TheAlgo** [comment]
@sastorsl As this PR comprises changes in `values.yaml`. We can bump the chart version here

**Comment by sastorsl** [comment]
> As this PR comprises changes in `values.yaml`. We can bump the chart version here

@TheAlgo I've re-added the version bump.
Is the selected version OK?

**Comment by prudhvigodithi** [comment]
look good for me @sastorsl 
@TheAlgo you mean to change the minor version here ?
We dont need to change (Again please correct me if i'm wrong), as we are not adding a new feature to `values.yaml`, but removing the depreciated one's.

**Comment by sastorsl** [comment]
> We dont need to change, as we are not adding a new feature to `values.yaml`

In the minimum it fails checks if not bumping though.
But please just advice and I'll add / remove / adjust version according to your feedback.

**Pull request merged**
