### PR TITLE
Opensearch and Dashboard Helm Charts support extra k8s Manifests

### PR DESCRIPTION
**Pull request by JunaidChaudry**
Opensearch and Dashboard Helm Charts support extra k8s Manifests

### Description
Providing a new addition, like many other opensource helm charts (e.g. grafana, prometheus, argo-cd), to support extra k8s manifests using the values files. 
This allows the end user to add any additional files needed to support their helm deployment. A nice use case now a days is to mount secrets on the fly by leveraging the Secrets Store CSI Driver.
 
### Issues Resolved
[#215 ]
 
### Check List
- [x] Commits are signed per the DCO using --signoff 
- [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
- [x]  I have updated the chart [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog) with all the changes that come with this pull request according to changelog.
- [x]  Any new values are backwards compatible and/or have sensible default.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by JunaidChaudry** [comment]
@peterzhuamazon @DandyDeveloper @TheAlgo

**Comment by peterzhuamazon** [comment]
@DandyDeveloper @TheAlgo please take a look when you are available. Thanks.

**Comment by DandyDeveloper** [comment]
@JunaidChaudry why are we doing this? The normal procedure for achieving this is having opensearch as the parent dependency. 

Then you can deploy whatever you need alongside opensearch. Can you show some examples of this being done elsewhere? To me this seems more restrictive then my above suggestion.

**Review by TheAlgo — COMMENTED** [review]
I have seen this feature in some other helm charts like Grafana but I am not a huge fan of this approach of having the deployments tightly coupled.

**Comment by peterzhuamazon** [comment]
@DandyDeveloper @TheAlgo any comments about the information above ^^?

Thanks.

**Comment by FernFerret** [comment]
As a user (and enjoyer!) of this helm chart, I'm in favor of this PR because I don't love creating more charts just to hold extra items. The `extraManifests` pattern allows me to quickly and intentionally couple items that need to be tightly coupled to run the chart like secrets and even custom ingress items (like a Traefik `Middleware` or `IngressRoute`) that are specific to both my deployment + opensearch.

**Comment by peterzhuamazon** [comment]
@DandyDeveloper @TheAlgo please review this PR when you available.
Ignore the version conflicts as I can fix it later.

Thanks.

**Comment by TheAlgo** [comment]
If there are users who are coupling some manifests as mentioned by @FernFerret. I don't have any major concerns with this feature. 

@DandyDeveloper @peterzhuamazon opinions?

**Comment by peterzhuamazon** [comment]
> If there are users who are coupling some manifests as mentioned by @FernFerret. I don't have any major concerns with this feature.
> 
> @DandyDeveloper @peterzhuamazon opinions?

I am not against it but I want others opinion as well.
@smlx @mprimeaux if you can take a look that would be great.
Thanks.

**Review by DandyDeveloper — APPROVED** [review]
I'll be honest, I'm not a fan. However, all for other people needing this. So I'll approve.

**Review by smlx — APPROVED** [review]
My initial response is negative, but thinking about it some more, having arbitrary objects is actually lower coupling than having specific templates for integration  with every third-party secrets store or other resource.

The alternative is to use a higher-level abstraction like [helmfile](https://github.com/roboll/helmfile), but I do see the utility of having this self-contained in the chart. So I also approve.

**Review by TheAlgo — APPROVED** [review]

**Pull request merged**
