### PR TITLE
s/kubernextes/kubernetes/g

### PR DESCRIPTION
**Pull request by daxxog**
Just a minor spelling thing.

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
@DandyDeveloper @TheAlgo do we still want to follow the rules of every simple change need a version bump?

**Comment by DandyDeveloper** [comment]
Honestly, I don't think its my call anymore @peterzhuamazon I've said several times I don't believe spell checks / README updates need to worry about it chart version increments. It will fail in CI though but we can use our judgement on approval for merging.

But, I am certain people disagree with me.

**Comment by TheAlgo** [comment]
> Honestly, I don't think its my call anymore @peterzhuamazon I've said several times I don't believe spell checks / README updates need to worry about it chart version increments. It will fail in CI though but we can use our judgement on approval for merging.
> 
> But, I am certain people disagree with me.

I remember quoting this in some PR , that we should not bump versions for README and spell checks and ignore CI failures or relax them. 

Link : https://github.com/opensearch-project/helm-charts/pull/152#issuecomment-984488161

**Review by TheAlgo — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Will wait a bit for this PR as I want to merge this right before another successful version bump so the pipeline will not show failure for a while.

**Comment by TheAlgo** [comment]
@daxxog Could you please sign off your commits because DCO checks are failing. Thanks

Ref : https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by daxxog** [comment]
> @daxxog Could you please sign off your commits because DCO checks are failing. Thanks
> 
> Ref : https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
Screen Shot 2022-01-05 at 10 32 51 PM

Yes, I did this commit quick TTW and it is signed with github's GPG key.

I do have git configured properly with GPG on my workstation and can amend my commit to use that GPG key if it helps with your CI checks.

**Comment by peterzhuamazon** [comment]
> > @daxxog Could you please sign off your commits because DCO checks are failing. Thanks
> > Ref : https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
> 
> Screen Shot 2022-01-05 at 10 32 51 PM
> 
> Yes, I did this commit quick TTW and it is signed with github's GPG key.
> 
> I do have git configured properly with GPG on my workstation and can amend my commit to use that GPG key if it helps with your CI checks.

We are talking about using `-s` for signing DCO, not about `-S` signing GPG those are two things.
Could you `git commit --amend --no-edit -s -S` then push again?
Thanks.

**Comment by daxxog** [comment]
@peterzhuamazon Just pulled down branch and re-signed with my key on my workstation -- pushed changed back up to origin. Used the command you posted, thanks for the tip!

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon Just pulled down branch and re-signed with my key on my workstation -- pushed changed back up to origin. Used the command you posted, thanks for the tip!

Thanks. DCO passed.
Ignore other failures you did not change code so lint is complaining version changes.

Will leave this here a bit and merge it once another PR with version change ready, so your PR wont block a release.

Thanks.

**Review by peterzhuamazon — APPROVED** [review]
Thanks.

**Pull request merged**
